function worldFile = exportGazeboWorld(worldFile)
%EXPORTGAZEBOWORLD Write a Gazebo world matching createWarehouseMap.
%   Generates an SDF world with the same geometry as the occupancy map
%   (outer walls, three shelf racks), the MathWorks co-simulation plugin
%   on port 14581, and a differential-drive robot with a lidar.
%   Robot joints: left_wheel_joint, right_wheel_joint. Default output is
%   gazebo/worlds/warehouse.world.

if nargin < 1
    worldFile = fullfile(fileparts(mfilename('fullpath')), ...
        '..', 'gazebo', 'worlds', 'warehouse.world');
end
outDir = fileparts(worldFile);
if ~isfolder(outDir)
    mkdir(outDir);
end

% Geometry must match createWarehouseMap: 50 x 30 m, walls, racks 2 m deep
% at y = 7..9, 14..16, 21..23 spanning x = 10..42
wallH = 2;
boxes = [ % cx cy sx sy  (centers and sizes, z spans 0..wallH)
    25  30   50  0.2;   % north wall
    25   0   50  0.2;   % south wall
     0  15  0.2   30;   % west wall
    50  15  0.2   30;   % east wall
    26   8   32    2;   % rack 1
    26  15   32    2;   % rack 2
    26  22   32    2];  % rack 3
names = ["wall_n" "wall_s" "wall_w" "wall_e" "rack_1" "rack_2" "rack_3"];

fid = fopen(worldFile, 'w');
assert(fid > 0, "Cannot open %s for writing", worldFile);
cleaner = onCleanup(@() fclose(fid));

fprintf(fid, '<?xml version="1.0"?>\n');
fprintf(fid, '<sdf version="1.6">\n<world name="warehouse">\n');

% Sun and ground plane are defined inline rather than included from the
% online model database, so the world loads with no network access (the
% co-sim container runs with --rm, so a model cache would not persist).
fprintf(fid, '  <light name="sun" type="directional">\n');
fprintf(fid, '    <cast_shadows>true</cast_shadows>\n');
fprintf(fid, '    <pose>0 0 10 0 0 0</pose>\n');
fprintf(fid, '    <diffuse>0.8 0.8 0.8 1</diffuse>\n');
fprintf(fid, '    <specular>0.2 0.2 0.2 1</specular>\n');
fprintf(fid, '    <direction>-0.5 0.1 -0.9</direction>\n');
fprintf(fid, '  </light>\n');
fprintf(fid, '  <model name="ground_plane">\n');
fprintf(fid, '    <static>true</static>\n');
fprintf(fid, '    <link name="link">\n');
fprintf(fid, '      <collision name="collision">\n');
fprintf(fid, '        <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>\n');
fprintf(fid, '        <surface><friction><ode><mu>100</mu><mu2>50</mu2></ode></friction></surface>\n');
fprintf(fid, '      </collision>\n');
fprintf(fid, '      <visual name="visual">\n');
fprintf(fid, '        <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>\n');
fprintf(fid, '      </visual>\n');
fprintf(fid, '    </link>\n');
fprintf(fid, '  </model>\n\n');

% MathWorks co-simulation plugin
fprintf(fid, '  <plugin name="GazeboPlugin" filename="lib/libGazeboCoSimPlugin.so">\n');
fprintf(fid, '    <portNumber>14581</portNumber>\n');
fprintf(fid, '  </plugin>\n\n');

% Default GUI camera: elevated view from the south edge looking at the
% warehouse centre, so the whole floor, racks, and robot are in frame.
fprintf(fid, '  <gui fullscreen="0">\n');
fprintf(fid, '    <camera name="user_camera">\n');
fprintf(fid, '      <pose>25 -20 40 0 0.85 1.5708</pose>\n');
fprintf(fid, '    </camera>\n');
fprintf(fid, '  </gui>\n\n');

% Static warehouse geometry
for k = 1:size(boxes, 1)
    fprintf(fid, '  <model name="%s">\n', names(k));
    fprintf(fid, '    <static>true</static>\n');
    fprintf(fid, '    <pose>%g %g %g 0 0 0</pose>\n', ...
        boxes(k,1), boxes(k,2), wallH/2);
    fprintf(fid, '    <link name="link">\n');
    fprintf(fid, '      <collision name="collision">\n');
    fprintf(fid, '        <geometry><box><size>%g %g %g</size></box></geometry>\n', ...
        boxes(k,3), boxes(k,4), wallH);
    fprintf(fid, '      </collision>\n');
    fprintf(fid, '      <visual name="visual">\n');
    fprintf(fid, '        <geometry><box><size>%g %g %g</size></box></geometry>\n', ...
        boxes(k,3), boxes(k,4), wallH);
    fprintf(fid, '      </visual>\n');
    fprintf(fid, '    </link>\n');
    fprintf(fid, '  </model>\n\n');
end

% Differential-drive robot with lidar, starting at the dock area
fprintf(fid, '%s\n', robotSDF(4, 4));

fprintf(fid, '</world>\n</sdf>\n');

fprintf("Wrote %s\n", worldFile);
end

function s = robotSDF(x, y)
s = sprintf([ ...
'  <model name="warehouse_robot">\n' ...
'    <pose>%g %g 0 0 0 0</pose>\n' ...
'    <link name="chassis">\n' ...
'      <pose>0 0 0.1 0 0 0</pose>\n' ...
'      <inertial>\n' ...
'        <mass>10</mass>\n' ...
'        <inertia><ixx>0.1</ixx><iyy>0.15</iyy><izz>0.2</izz>\n' ...
'          <ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia>\n' ...
'      </inertial>\n' ...
'      <collision name="collision">\n' ...
'        <geometry><box><size>0.4 0.3 0.1</size></box></geometry>\n' ...
'      </collision>\n' ...
'      <visual name="visual">\n' ...
'        <geometry><box><size>0.4 0.3 0.1</size></box></geometry>\n' ...
'        <material><ambient>1 0.45 0 1</ambient><diffuse>1 0.45 0 1</diffuse></material>\n' ...
'      </visual>\n' ...
'      <visual name="beacon">\n' ...
'        <pose>0 0 0.85 0 0 0</pose>\n' ...
'        <geometry><box><size>0.25 0.25 1.6</size></box></geometry>\n' ...
'        <material><ambient>1 0.45 0 1</ambient><diffuse>1 0.45 0 1</diffuse></material>\n' ...
'      </visual>\n' ...
'      <collision name="caster">\n' ...
'        <pose>-0.15 0 -0.05 0 0 0</pose>\n' ...
'        <geometry><sphere><radius>0.05</radius></sphere></geometry>\n' ...
'        <surface><friction><ode><mu>0</mu><mu2>0</mu2></ode></friction></surface>\n' ...
'      </collision>\n' ...
'      <visual name="caster_visual">\n' ...
'        <pose>-0.15 0 -0.05 0 0 0</pose>\n' ...
'        <geometry><sphere><radius>0.05</radius></sphere></geometry>\n' ...
'      </visual>\n' ...
'    </link>\n' ...
'    <link name="left_wheel">\n' ...
'      <pose>0.1 0.17 0.1 -1.5707 0 0</pose>\n' ...
'      <inertial>\n' ...
'        <mass>1</mass>\n' ...
'        <inertia><ixx>0.003</ixx><iyy>0.003</iyy><izz>0.005</izz>\n' ...
'          <ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia>\n' ...
'      </inertial>\n' ...
'      <collision name="collision">\n' ...
'        <geometry><cylinder><radius>0.1</radius><length>0.05</length></cylinder></geometry>\n' ...
'      </collision>\n' ...
'      <visual name="visual">\n' ...
'        <geometry><cylinder><radius>0.1</radius><length>0.05</length></cylinder></geometry>\n' ...
'      </visual>\n' ...
'    </link>\n' ...
'    <link name="right_wheel">\n' ...
'      <pose>0.1 -0.17 0.1 -1.5707 0 0</pose>\n' ...
'      <inertial>\n' ...
'        <mass>1</mass>\n' ...
'        <inertia><ixx>0.003</ixx><iyy>0.003</iyy><izz>0.005</izz>\n' ...
'          <ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia>\n' ...
'      </inertial>\n' ...
'      <collision name="collision">\n' ...
'        <geometry><cylinder><radius>0.1</radius><length>0.05</length></cylinder></geometry>\n' ...
'      </collision>\n' ...
'      <visual name="visual">\n' ...
'        <geometry><cylinder><radius>0.1</radius><length>0.05</length></cylinder></geometry>\n' ...
'      </visual>\n' ...
'    </link>\n' ...
'    <joint type="revolute" name="left_wheel_joint">\n' ...
'      <child>left_wheel</child>\n' ...
'      <parent>chassis</parent>\n' ...
'      <axis><xyz>0 0 1</xyz></axis>\n' ...
'    </joint>\n' ...
'    <joint type="revolute" name="right_wheel_joint">\n' ...
'      <child>right_wheel</child>\n' ...
'      <parent>chassis</parent>\n' ...
'      <axis><xyz>0 0 1</xyz></axis>\n' ...
'    </joint>\n' ...
'    <link name="lidar">\n' ...
'      <pose>0.15 0 0.2 0 0 0</pose>\n' ...
'      <inertial>\n' ...
'        <mass>0.1</mass>\n' ...
'        <inertia><ixx>0.0001</ixx><iyy>0.0001</iyy><izz>0.0001</izz>\n' ...
'          <ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia>\n' ...
'      </inertial>\n' ...
'      <visual name="visual">\n' ...
'        <geometry><cylinder><radius>0.03</radius><length>0.04</length></cylinder></geometry>\n' ...
'      </visual>\n' ...
'      <sensor name="lidar" type="ray">\n' ...
'        <always_on>true</always_on>\n' ...
'        <update_rate>10</update_rate>\n' ...
'        <ray>\n' ...
'          <scan><horizontal>\n' ...
'            <samples>640</samples>\n' ...
'            <resolution>1</resolution>\n' ...
'            <min_angle>-2.356</min_angle>\n' ...
'            <max_angle>2.356</max_angle>\n' ...
'          </horizontal></scan>\n' ...
'          <range><min>0.12</min><max>8</max></range>\n' ...
'        </ray>\n' ...
'      </sensor>\n' ...
'    </link>\n' ...
'    <joint type="fixed" name="lidar_joint">\n' ...
'      <child>lidar</child>\n' ...
'      <parent>chassis</parent>\n' ...
'    </joint>\n' ...
'  </model>'], x, y);
end
